<a href="https://colab.research.google.com/github/tiwarisubash956/Machine-Learning-Algorithms/blob/main/text_classification_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

In [7]:
temp_df = pd.read_csv(
    "/content/IMDB Dataset.csv",
    engine="python",
    on_bad_lines="skip"
)

In [8]:
temp_df.shape

(50000, 2)

In [9]:
temp_df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [10]:
df=temp_df.iloc[:10000]

In [11]:
df.shape

(10000, 2)

In [12]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [13]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(17)

In [15]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_3747/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
# preprocessing
# remove tags
# lower case
# remove stop words

In [18]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [19]:
def remove_tags(text):
  # remove tags
  cleaned_text = re.sub(re.compile('<.*?>'), '', text)
  # lower case
  return cleaned_text

In [20]:
df['review']=df['review'].apply(remove_tags)

/tmp/ipykernel_3747/2928534252.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(remove_tags)

In [21]:
#  upper case to lower case
df['review']=df['review'].apply(lambda x:x.lower())

/tmp/ipykernel_3747/2708510413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x:x.lower())

In [22]:
# remove stop list
sw_list = stopwords.words('english')
df['review']=df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

/tmp/ipykernel_3747/2068723887.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review']=df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [23]:
X=df.iloc[:,0:1]
y=df.iloc[:,-1]

In [24]:
# label encoder
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X_train_bow = cv.fit_transform(X_train.iloc[:,0]).toarray()
X_test_bow = cv.transform(X_test.iloc[:,0]).toarray()

In [28]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score
model = GaussianNB()
model.fit(X_train_bow,y_train)
#

GaussianNB()

In [29]:
y_pred=model.predict(X_test_bow)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(precision_score(y_test,y_pred))

0.6129193790686029
[[701 296]
 [477 523]]
0.6385836385836385

In [30]:
confusion_matrix(y_test,y_pred)

array([[701, 296],
       [477, 523]])

In [33]:
from sklearn.ensemble import RandomForestClassifier
model2 = RandomForestClassifier()
model2.fit(X_train_bow,y_train)
y_pred=model2.predict(X_test_bow)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(precision_score(y_test,y_pred))

0.8472709063595393
[[849 148]
 [157 843]]
0.8506559031281534

In [35]:
cv=CountVectorizer(max_features=3000)
X_train_bow=cv.fit_transform(X_train.iloc[:,0]).toarray()
X_test_bow=cv.transform(X_test.iloc[:,0]).toarray()

rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
print(accuracy_score(y_test,y_pred))

0.8467701552328493

**using tfldf**

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [37]:
X_train_tfidf=tfidf.fit_transform(X_train.iloc[:,0]).toarray()
X_test_tfidf=tfidf.transform(X_test.iloc[:,0]).toarray()

In [38]:
rf=RandomForestClassifier()
rf.fit(X_train_tfidf,y_train)
y_pred=rf.predict(X_test_tfidf)
print(accuracy_score(y_test,y_pred))

0.8432648973460191